### ISSUE TITLE
Think about code structure

### ISSUE THREAD

**Issue by sekkurocode** [sekkurocode/Cellular-Automata#3]
Which classes, functions and variables do we need to realize this project. Collect your thoughts and have them ready by next weeks meeting.

**Comment by Sara25s** [comment]
Hey, ich habe euch letzte Woche Kanban-Board geschickt aber ihr habt sich  noch nicht reagiert .

**Comment by Sara25s** [comment]
https://github.com/users/Sara25s/projects/1/views/1

**Comment by sekkurocode** [comment]
Hey, i didn't know and didn't get notified that you already opened a kanban board for us. If you want you can migrate the issues you created to the kanban board i opened in our cellular-automata repository. We discussed the issues and assignments at our last weekly meeting :)
