### ISSUE TITLE
W1: most basic code structure and to do

### ISSUE THREAD

**Issue by fabrice-eberle** [sekkurocode/Cellular-Automata#5]
what a game loop should do on the most basic level:

Board (empty np zeros) -> class 

create random distribution in Start class

board (np array_random_distribution)

def check (checking every cell, if sum of neighbors >3 , =2 or <2)
if (
Li(t) = {1 if sumj oj = 3
{o(t) if sumj oj = 2
{0 otherwise
)   ----> o is the cell, value is saved on a **temporary board**

board = temporary board

restart

Please comment with the part of the code that you are working on.

We also need to create a test for the basic code.

**Comment by sekkurocode** [comment]
I'm gonna define the classes and their __init__ functions. So parameters like rules of survival and such.

**Comment by Sara25s** [comment]
I´m gonna  work on the Game Classe
